version: '3'

services:
  db:
    image: 'mariadb:10.1'
    volumes:
      - data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=t3kit
      - MYSQL_PASSWORD=t3kit1234
      - MYSQL_DATABASE=t3kit
    ports:
      - "3308:3306"

  mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  t3kit:
    image: 't3kit/t3kit:latest'
    volumes:
      - ./shared:/var/www/shared
    ports:
      - "8082:80"
    links:
      - db
      - mail

volumes:
  data: {}
